url: "https://sunderb.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/mlh-init-2022" # the subpath of your site, e.g. /blog
title: "MLH Init 2022 - SunderB's Website" # the name of your site, e.g. ACME Corp.
